export type Locale = 'es' | 'en' | 'pt' | 'it'

export interface Translations {
  sidebar: {
    menu: string; principal: string; services: string
    settings: string; home: string; speech: string; campaigns: string
    reports: string; billing: string
  }
  settings: { title: string; profiles: string; users: string; permissions: string }
  actions: {
    save: string; cancel: string; create: string; edit: string; delete: string
    update: string; close: string; search: string; saving: string; loading: string
    new: string; confirm: string; activate: string; deactivate: string; filters: string
    export: string; exportXlsx: string; exportPdf: string; apply: string; clearFilters: string
    add: string; saveChanges: string; reanalyzeText: string
  }
  labels: {
    name: string; email: string; password: string; company: string; username: string
    firstName: string; lastName: string; photo: string; code: string
    active: string; inactive: string; assignedProfiles: string; noProfiles: string
    myPermissions: string; noPermissions: string; fromProfile: string
    added: string; removed: string; recordings: string; analyzed: string
    inProgress: string; errors: string; noCampaigns: string; noRecordings: string
    status: string; campaign: string; user: string; dateFrom: string; dateTo: string
    allCampaigns: string; allUsers: string; allStatuses: string;
    statusCampaignGood: string; statusCampaignRegular: string; statusCampaignImprove: string
  }
  userMenu: {
    myProfile: string; assignedProfiles: string; noProfiles: string
    changePassword: string; logout: string; logoutConfirmTitle: string
    logoutConfirmText: string; logoutConfirmBtn: string; newPassword: string
    confirmPassword: string; updatePassword: string; passwordMinLength: string
    passwordMismatch: string; passwordUpdated: string; passwordUpdatedText: string
    language: string
  }
  users: {
    title: string; newUser: string; editUser: string; createUser: string
    noUsers: string; noUsersHint: string; searchByUser: string; searchByCompany: string
    searching: string; profiles: string; deleteConfirmTitle: string
    deleteConfirmText: string; userCreated: string; userUpdated: string
    userDeleted: string; profilePhoto: string
  }
  profiles: {
    title: string; newProfile: string; editProfile: string; createProfile: string
    noProfiles: string; noProfilesHint: string; profileName: string; permissions: string
    searchUser: string; editUser: string; assignedProfiles: string
    individualPermissions: string; permissionLegend: string; deleteConfirmTitle: string
    deleteConfirmText: string; profileCreated: string; profileUpdated: string; usersAssigned: string
  }
  permissions: {
    title: string; newPermission: string; editPermission: string; createPermission: string
    noPermissions: string; noPermissionsHint: string; permissionName: string
    permissionCode: string; assignToUser: string; deleteConfirmTitle: string
    permissionCreated: string; permissionUpdated: string
  }
  campaigns: {
    title: string; newCampaign: string; editCampaign: string; noData: string
    viewRecordings: string; viewIndicators: string; deleteConfirmTitle: string
    deleteConfirmText: string; campaignCreated: string; campaignUpdated: string
    campaignDeleted: string; campaignActivated: string; campaignDeactivated: string
    saveIndicators: string; savingIndicators: string; errorLoading: string
    errorSaving: string; errorDeleting: string; errorStatus: string; promptEvaluation: string
    instructionPrompt: string; allowedUsers: string; allowedUsersHint: string
    minutesLimit: string; minutesLimitHint: string; minutesLimitMax: string
    minutesConsumed: string; minutesLimitReached: string; minutesLimitWarning: string
    modify: string; selectUsers: string; noneSelected: string; selectVisible: string
    deselectVisible: string; searchUsers: string; noUsersSelected: string; selectAllowed: string
  }
  indicatorForm: {
    title: string; titleSing: string; newIndicator: string; editingIndicator: string
    indicatorName: string; namePlaceholder: string; scoreIfMeets: string
    scoreIfNotMeets: string; condition: string; selectCondition: string
    description: string; descriptionPlaceholder: string
    noIndicators: string; noIndicatorsHint: string
    // v2 — modal + textarea grande
    criteriaLabel: string   // badge en mini card cuando hay descripcion cargada
    criteriaHint: string    // hint debajo del textarea explicando el proposito del campo
  }
  speech: {
    title: string; upload: string; transcribe: string; newAudio: string
    uploadAudio: string; processing: string; analyzing: string; selectAudio: string
    audioFormats: string; audioProcessed: string; qualityIndicators: string
    transcription: string; summary: string; sentiment: string; score: string
    duration: string; analysisResult: string
    reviewIndicator: string; previewOnly: string; gemini: string
    originalScore: string; lastReview: string; evidence: string
    meetsIndicator: string; yes: string; no: string; meets: string; doesNotMeet: string
    assignedScore: string; range: string; auditorNote: string; optional: string
    notePlaceholder: string; saveReview: string; applyChanges: string
    formatInvalid: string; formatInvalidText: string; errorUploading: string
    errorUploadText: string; errorAnalyzing: string; errorAnalyzeText: string
    reviewSaved: string; errorSavingReview: string; errorSavingReviewText: string
    resolution: string; resolved: string; noResolution: string
    compliance: string; script: string; scriptMeets: string; scriptFails: string
    errors: string; conformity: string; applyOk: string; points: string
    noEvidenceFound: string; audited: string; markAsAudited: string;
    alreadyAudited: string; auditError: string; Reanalyze: string;
  }
  reports: {
    title: string; subtitle: string
    filters: string; filtersTitle: string
    campaign: string; user: string; dateFrom: string; dateTo: string
    apply: string; clearFilters: string
    totalCalls: string; analyzedCalls: string; avgScore: string; avgDuration: string
    scoreDistribution: string; callsByUser: string; callsByCampaign: string
    callsOverTime: string; sentimentDistribution: string; wordCloud: string
    topWords: string; noData: string; noDataDesc: string
    exportXlsx: string; exportPdf: string
    exporting: string; exportSuccess: string; exportError: string
    scoreLabel: string; countLabel: string; userLabel: string
    dateLabel: string; campaignLabel: string; sentimentLabel: string
    positive: string; neutral: string; negative: string; satisfied: string; unsatisfied: string
    callName: string; status: string; score: string; duration: string; date: string
    summary: string; reportTitle: string; generatedOn: string; appliedFilters: string
    allCampaigns: string; allUsers: string; indicator: string; compliance: string; points: string
    indicators: string; indicatorReport: string; callDetail: string
    periodFrom: string; periodTo: string; totalIndicators: string
    avgCompliance: string; topIndicators: string; worstIndicators: string; indicatorRanking: string
  }
  login: {
    welcome: string; subtitle: string; emailPlaceholder: string; passwordPlaceholder: string
    loginButton: string; recoverPassword: string; loggingIn: string
    errorTitle: string; errorText: string
  }
  dashboard: { title: string; contactAdmin: string; welcome: string }
  errors: { generic: string; notFound: string; forbidden: string }
  billing: {
    title: string; adminSubtitle: string; clientSubtitle: string
    pricePerMin: string; period: string; periodStart: string; days: string
    periodNotSet: string; notConfigured: string
    renewsIn: string; renewNow: string; renewConfirm: string
    renewSuccess: string; reactivated: string
    minutes: string; minutesUsed: string; limit: string; noLimit: string
    geminiCost: string; clientPrice: string; margin: string; subtotal: string
    totalMinutes: string; geminiCostTotal: string; totalToBill: string; totalMargin: string
    allCampaigns: string; toClients: string; currentPeriod: string; estimatedTotal: string
    detailByCampaign: string; noCampaigns: string; noPriceWarning: string; noData: string
    renewConfirmTitle: string; renewConfirmText: string; renewedTitle: string
    filterTitle: string; filterPeriod: string; filterFrom: string; filterTo: string
    selectDate: string; campaignWord: string; configTitle?: string
  }
}

// ─── Español ───────────────────────────────────────────────────────────────
const es: Translations = {
  sidebar: { menu: 'Menú', principal: 'Principal', services: 'Servicios', settings: 'Configuraciones', home: 'Inicio', speech: 'Speech', campaigns: 'Campañas', reports: 'Reportes', billing: 'Facturación' },
  settings: { title: 'Configuraciones', profiles: 'Perfiles', users: 'Usuarios', permissions: 'Permisos' },
  actions: { save: 'Guardar', cancel: 'Cancelar', create: 'Crear', edit: 'Editar', delete: 'Eliminar', update: 'Actualizar', close: 'Cerrar', search: 'Buscar', saving: 'Guardando...', loading: 'Cargando...', new: 'Nuevo', confirm: 'Confirmar', activate: 'Activar', deactivate: 'Desactivar', filters: 'Limpiar filtros', export: 'Exportar', exportXlsx: 'Exportar Excel', exportPdf: 'Exportar PDF', apply: 'Aplicar', clearFilters: 'Limpiar filtros', add: 'Agregar', saveChanges: 'Guardar cambios', reanalyzeText: 'Se borrará el análisis actual y la grabación será procesada nuevamente. ¿Continuar?' },
  labels: { statusCampaignImprove: '✗ A mejorar', statusCampaignRegular: '~ Regular', statusCampaignGood: '✓ Bueno', name: 'Nombre', email: 'Email', password: 'Contraseña', company: 'Empresa', username: 'Usuario', firstName: 'Nombre', lastName: 'Apellido', photo: 'Foto de perfil', code: 'Código', active: 'Activa', inactive: 'Inactiva', assignedProfiles: 'Perfiles asignados', noProfiles: 'Sin perfiles asignados', myPermissions: 'Mis Permisos', noPermissions: 'No tenés permisos asignados', fromProfile: 'Del perfil', added: '+ Añadido', removed: '- Removido', recordings: 'Grabaciones', analyzed: 'Analizadas', inProgress: 'En proceso', errors: 'Errores', noCampaigns: 'Sin datos de campañas aún', noRecordings: 'Sin grabaciones analizadas aún', status: 'Estado', campaign: 'Campaña', user: 'Usuario', dateFrom: 'Desde', dateTo: 'Hasta', allCampaigns: 'Todas las campañas', allUsers: 'Todos los usuarios', allStatuses: 'Todos los estados' },
  userMenu: { myProfile: 'Mi Perfil', assignedProfiles: 'Perfiles asignados', noProfiles: 'No tienes perfiles asignados', changePassword: 'Modificar Contraseña', logout: 'Cerrar Sesión', logoutConfirmTitle: '¿Cerrar sesión?', logoutConfirmText: '¿Estás seguro de que deseas cerrar sesión?', logoutConfirmBtn: 'Sí, cerrar sesión', newPassword: 'Nueva Contraseña', confirmPassword: 'Confirmar Nueva Contraseña', updatePassword: 'Actualizar Contraseña', passwordMinLength: 'La contraseña debe tener al menos 6 caracteres', passwordMismatch: 'Las contraseñas no coinciden', passwordUpdated: '¡Contraseña actualizada!', passwordUpdatedText: 'Tu contraseña se ha actualizado correctamente', language: 'Idioma' },
  users: { title: 'Gestión de Usuarios', newUser: 'Nuevo Usuario', editUser: 'Editar Usuario', createUser: 'Crear Usuario', noUsers: 'No hay usuarios', noUsersHint: 'Crea un nuevo usuario con el botón "Nuevo Usuario"', searchByUser: 'Buscar por usuario...', searchByCompany: 'Buscar por empresa...', searching: 'Buscando...', profiles: 'Perfiles:', deleteConfirmTitle: '¿Eliminar usuario?', deleteConfirmText: 'Esta acción no se puede deshacer', userCreated: '¡Usuario creado!', userUpdated: '¡Usuario actualizado!', userDeleted: '¡Usuario eliminado!', profilePhoto: 'Foto de perfil' },
  profiles: { title: 'Gestión de Perfiles', newProfile: 'Nuevo Perfil', editProfile: 'Editar Perfil', createProfile: 'Crear Perfil', noProfiles: 'No hay perfiles', noProfilesHint: 'Crea un nuevo perfil con el botón "Nuevo Perfil"', profileName: 'Nombre del Perfil*', permissions: 'Permisos:', searchUser: 'Buscar usuario por nombre o username...', editUser: 'Buscar y Modificar Usuario', assignedProfiles: 'Perfiles asignados:', individualPermissions: 'Permisos individuales:', permissionLegend: '✓ Verde = Del perfil | + Añadido | - Removido', deleteConfirmTitle: '¿Eliminar perfil?', deleteConfirmText: 'Esta acción no se puede deshacer', profileCreated: '¡Perfil creado!', profileUpdated: '¡Perfil actualizado!', usersAssigned: 'usuario(s) asignado(s)' },
  permissions: { title: 'Gestión de Permisos', newPermission: 'Nuevo Permiso', editPermission: 'Editar Permiso', createPermission: 'Crear Permiso', noPermissions: 'No hay permisos', noPermissionsHint: 'Crea un nuevo permiso con el botón "Nuevo Permiso"', permissionName: 'Nombre del Permiso*', permissionCode: 'Código*', assignToUser: 'Asignar Permisos a Usuario', deleteConfirmTitle: '¿Eliminar permiso?', permissionCreated: '¡Permiso creado!', permissionUpdated: '¡Permiso actualizado!' },
  campaigns: { title: 'Campañas', newCampaign: 'Nueva Campaña', editCampaign: 'Editar campaña', noData: 'No hay campañas', viewRecordings: 'Ver grabaciones', viewIndicators: 'Ver y editar indicadores', deleteConfirmTitle: '¿Eliminar campaña?', deleteConfirmText: 'Esta acción no se puede deshacer', campaignCreated: '¡Campaña creada!', campaignUpdated: '¡Campaña actualizada!', campaignDeleted: '¡Campaña eliminada!', campaignActivated: '¡Campaña activada!', campaignDeactivated: 'Campaña desactivada', saveIndicators: 'Guardar indicadores', savingIndicators: 'Guardando...', errorLoading: 'No se pudieron cargar las campañas', errorSaving: 'No se pudo guardar la campaña', errorDeleting: 'No se pudo eliminar la campaña', errorStatus: 'No se pudo actualizar el estado', promptEvaluation: 'Prompt de evaluación', instructionPrompt: 'Instrucciones para el modelo de IA...', allowedUsers: 'Usuarios permitidos', allowedUsersHint: 'Solo los usuarios seleccionados podrán ver esta campaña, sus análisis y reportes.', minutesLimit: 'Límite de minutos transcriptos', minutesLimitHint: 'Al alcanzar este límite, la campaña se inactivará automáticamente.', minutesLimitMax: 'Máximo de minutos', minutesConsumed: 'Minutos consumidos', minutesLimitReached: '⚠ Límite alcanzado — la campaña está inactiva.', minutesLimitWarning: '⚠ La campaña se inactivará al alcanzar el límite configurado.', modify: 'Modificar', selectUsers: 'Seleccionar usuarios', noneSelected: 'Ninguno seleccionado', selectVisible: 'Seleccionar visibles', deselectVisible: 'Deseleccionar visibles', searchUsers: 'Buscar por nombre, email o usuario...', noUsersSelected: 'Sin usuarios seleccionados — solo los admins verán la campaña.', selectAllowed: 'Seleccionar usuarios permitidos' },
  indicatorForm: {
    title: 'Indicadores', titleSing: 'Indicador', newIndicator: 'Nuevo indicador',
    editingIndicator: 'Editando indicador', indicatorName: 'Nombre',
    namePlaceholder: 'Ej: Saludo cordial', scoreIfMeets: 'Puntaje si cumple',
    scoreIfNotMeets: 'Puntaje si no cumple', condition: 'Condición',
    selectCondition: 'Seleccionar condición', description: 'Criterio para Gemini',
    descriptionPlaceholder: 'Describí en detalle qué debe buscar Gemini para evaluar este indicador. Podés incluir ejemplos, condiciones de activación y casos borde.',
    noIndicators: 'No hay indicadores.', noIndicatorsHint: 'Agregá al menos uno.',
    criteriaLabel: 'criterio',
    criteriaHint: 'Instrucciones precisas que se envían a Gemini para evaluar este indicador. Podés incluir criterios, ejemplos o condiciones de activación.',
  },
  speech: { title: 'Speech Analytics', upload: 'Subir Audio', transcribe: 'Transcribir', newAudio: 'Nuevo Audio', uploadAudio: 'Subir Audio', processing: 'Procesando...', analyzing: 'Analizando...', selectAudio: 'Hacé clic para seleccionar un audio', audioFormats: 'MP3, WAV, M4A, OGG — máx. 50MB', audioProcessed: 'Audio procesado', qualityIndicators: 'Indicadores de Calidad', transcription: 'Transcripción', summary: 'Resumen', sentiment: 'Sentimiento', score: 'Puntaje', duration: 'Duración', analysisResult: 'Resultado del análisis', reviewIndicator: 'Revisión de indicador', previewOnly: 'Solo vista previa', gemini: 'Gemini', originalScore: 'Puntaje original', lastReview: 'Última revisión', evidence: 'Evidencia', meetsIndicator: '¿Cumple el indicador?', yes: 'Sí', no: 'No', meets: 'Sí, cumple', doesNotMeet: 'No cumple', assignedScore: 'Puntaje asignado', range: 'rango', auditorNote: 'Nota del auditor', optional: 'opcional', notePlaceholder: 'Justificación o comentario sobre la revisión...', saveReview: 'Guardar revisión', applyChanges: 'Aplicar cambios', formatInvalid: 'Formato inválido', formatInvalidText: 'Solo se permiten archivos de audio', errorUploading: 'Error al subir', errorUploadText: 'No se pudo procesar el audio', errorAnalyzing: 'Error al analizar', errorAnalyzeText: 'No se pudo obtener la transcripción', reviewSaved: 'Revisión guardada', errorSavingReview: 'Error', errorSavingReviewText: 'No se pudo guardar la revisión.', resolution: 'Resolución', resolved: 'Resuelto', noResolution: 'Sin resolución', compliance: 'Cumplimiento', script: 'Script', scriptMeets: 'Cumple', scriptFails: 'No cumple', errors: 'Errores', conformity: 'Conformidad', applyOk: 'Aplican OK', points: 'pts', noEvidenceFound: 'No se encontró evidencia en el audio', audited: 'Auditada', markAsAudited: 'Marcar como auditada', alreadyAudited: 'Auditada por', auditError: 'No se pudo marcar como auditada', Reanalyze: 'Re-analizar con Gemini' },
  reports: { title: 'Reportes', subtitle: 'Análisis y estadísticas de campañas', filters: 'Filtros', filtersTitle: 'Filtros del reporte', campaign: 'Campaña', user: 'Usuario', dateFrom: 'Fecha desde', dateTo: 'Fecha hasta', apply: 'Aplicar filtros', clearFilters: 'Limpiar filtros', totalCalls: 'Total grabaciones', analyzedCalls: 'Analizadas', avgScore: 'Puntaje promedio', avgDuration: 'Duración promedio', scoreDistribution: 'Distribución de puntajes', callsByUser: 'Grabaciones por usuario', callsByCampaign: 'Grabaciones por campaña', callsOverTime: 'Evolución temporal', sentimentDistribution: 'Distribución de sentimientos', wordCloud: 'Nube de palabras', topWords: 'Palabras frecuentes', noData: 'Sin datos', noDataDesc: 'No hay grabaciones analizadas con los filtros seleccionados', exportXlsx: 'Exportar Excel', exportPdf: 'Exportar PDF', exporting: 'Exportando...', exportSuccess: '¡Exportado exitosamente!', exportError: 'Error al exportar', scoreLabel: 'Puntaje', countLabel: 'Cantidad', userLabel: 'Usuario', dateLabel: 'Fecha', campaignLabel: 'Campaña', sentimentLabel: 'Sentimiento', positive: 'Positivo', neutral: 'Neutral', negative: 'Negativo', satisfied: 'Satisfecho', unsatisfied: 'Insatisfecho', callName: 'Grabación', status: 'Estado', score: 'Puntaje', duration: 'Duración', date: 'Fecha', summary: 'Resumen', reportTitle: 'Reporte de Campañas', generatedOn: 'Generado el', appliedFilters: 'Filtros aplicados', allCampaigns: 'Todas las campañas', allUsers: 'Todos los usuarios', indicator: 'Indicador', compliance: 'Cumplimiento', points: 'Puntos', indicators: 'Indicadores', indicatorReport: 'Reporte de indicadores', callDetail: 'Detalle de grabaciones', periodFrom: 'Período desde', periodTo: 'hasta', totalIndicators: 'Total indicadores', avgCompliance: 'Cumplimiento promedio', topIndicators: 'Mejores indicadores', worstIndicators: 'Indicadores a mejorar', indicatorRanking: 'Ranking de indicadores' },
  login: { welcome: 'Bienvenido', subtitle: 'Ingresa tus credenciales para continuar', emailPlaceholder: 'email', passwordPlaceholder: 'contraseña', loginButton: 'Iniciar Sesión', recoverPassword: 'Recuperar Contraseña', loggingIn: 'Iniciando sesión...', errorTitle: 'Error de autenticación', errorText: 'Usuario o contraseña incorrectos' },
  dashboard: { title: 'Dashboard', contactAdmin: 'Contactá a un administrador', welcome: 'Bienvenido' },
  errors: { generic: 'Error', notFound: 'No encontrado', forbidden: 'Sin acceso' },
  billing: { title: 'Facturación', adminSubtitle: 'Costos, precios y márgenes por campaña', clientSubtitle: 'Resumen de consumo de minutos transcriptos', pricePerMin: 'Precio / min', period: 'Período', periodStart: 'Inicio del período', days: 'Días', periodNotSet: 'No configurado', notConfigured: 'No config.', renewsIn: 'Renueva en {n}d', renewNow: 'Renovar ahora', renewConfirm: '¿Renovar el período de "{name}" ahora?\nSe resetearán los minutos y se reactivará la campaña si estaba inactiva por límite.', renewSuccess: 'Período renovado. {discarded} grabaciones descartadas.', reactivated: 'Campaña reactivada.', minutes: 'Minutos', minutesUsed: 'Minutos usados', limit: 'Límite', noLimit: 'Sin límite', geminiCost: 'Costo Gemini', clientPrice: 'A facturar', margin: 'Margen', subtotal: 'Subtotal', totalMinutes: 'Minutos totales', geminiCostTotal: 'Costo Gemini total', totalToBill: 'A facturar total', totalMargin: 'Margen total', allCampaigns: 'Todas las campañas', toClients: 'a clientes', currentPeriod: 'total del período', estimatedTotal: 'Total estimado', detailByCampaign: 'Detalle por campaña', noCampaigns: 'No hay campañas configuradas.', noPriceWarning: 'Algunas campañas no tienen precio configurado. Contactá a tu administrador.', noData: 'Sin datos disponibles.', renewConfirmTitle: '¿Renovar período?', renewConfirmText: 'Los minutos se resetearán y la campaña se reactivará si estaba inactiva por límite.', renewedTitle: 'Período renovado', filterTitle: 'Filtrar facturación', filterPeriod: 'Período', filterFrom: 'Desde...', filterTo: 'Hasta...', selectDate: 'Seleccionar...', campaignWord: 'campañas', configTitle: 'Configurar' },
}

// ─── English ───────────────────────────────────────────────────────────────
const en: Translations = {
  sidebar: { menu: 'Menu', principal: 'Main', services: 'Services', settings: 'Settings', home: 'Home', speech: 'Speech', campaigns: 'Campaigns', reports: 'Reports', billing: 'Billing' },
  settings: { title: 'Settings', profiles: 'Profiles', users: 'Users', permissions: 'Permissions' },
  actions: { save: 'Save', cancel: 'Cancel', create: 'Create', edit: 'Edit', delete: 'Delete', update: 'Update', close: 'Close', search: 'Search', saving: 'Saving...', loading: 'Loading...', new: 'New', confirm: 'Confirm', activate: 'Activate', deactivate: 'Deactivate', filters: 'Clean filters', export: 'Export', exportXlsx: 'Export Excel', exportPdf: 'Export PDF', apply: 'Apply', clearFilters: 'Clear filters', add: 'Add', saveChanges: 'Save changes', reanalyzeText: 'The current analysis will be deleted and the recording will be processed again. Continue?' },
  labels: { statusCampaignImprove: '✗ Needs improvement', statusCampaignRegular: '~ Regular', statusCampaignGood: '✓ Good', name: 'Name', email: 'Email', password: 'Password', company: 'Company', username: 'Username', firstName: 'First name', lastName: 'Last name', photo: 'Profile photo', code: 'Code', active: 'Active', inactive: 'Inactive', assignedProfiles: 'Assigned profiles', noProfiles: 'No profiles assigned', myPermissions: 'My Permissions', noPermissions: 'You have no permissions assigned', fromProfile: 'From profile', added: '+ Added', removed: '- Removed', recordings: 'Recordings', analyzed: 'Analyzed', inProgress: 'In progress', errors: 'Errors', noCampaigns: 'No campaign data yet', noRecordings: 'No analyzed recordings yet', status: 'Status', campaign: 'Campaign', user: 'User', dateFrom: 'From', dateTo: 'To', allCampaigns: 'All campaigns', allUsers: 'All users', allStatuses: 'All statuses' },
  userMenu: { myProfile: 'My Profile', assignedProfiles: 'Assigned profiles', noProfiles: 'No profiles assigned', changePassword: 'Change Password', logout: 'Log Out', logoutConfirmTitle: 'Log out?', logoutConfirmText: 'Are you sure you want to log out?', logoutConfirmBtn: 'Yes, log out', newPassword: 'New Password', confirmPassword: 'Confirm New Password', updatePassword: 'Update Password', passwordMinLength: 'Password must be at least 6 characters', passwordMismatch: 'Passwords do not match', passwordUpdated: 'Password updated!', passwordUpdatedText: 'Your password has been updated successfully', language: 'Language' },
  users: { title: 'User Management', newUser: 'New User', editUser: 'Edit User', createUser: 'Create User', noUsers: 'No users found', noUsersHint: 'Create a new user with the "New User" button', searchByUser: 'Search by username...', searchByCompany: 'Search by company...', searching: 'Searching...', profiles: 'Profiles:', deleteConfirmTitle: 'Delete user?', deleteConfirmText: 'This action cannot be undone', userCreated: 'User created!', userUpdated: 'User updated!', userDeleted: 'User deleted!', profilePhoto: 'Profile photo' },
  profiles: { title: 'Profile Management', newProfile: 'New Profile', editProfile: 'Edit Profile', createProfile: 'Create Profile', noProfiles: 'No profiles found', noProfilesHint: 'Create a new profile with the "New Profile" button', profileName: 'Profile Name*', permissions: 'Permissions:', searchUser: 'Search user by name or username...', editUser: 'Search & Edit User', assignedProfiles: 'Assigned profiles:', individualPermissions: 'Individual permissions:', permissionLegend: '✓ Green = From profile | + Added | - Removed', deleteConfirmTitle: 'Delete profile?', deleteConfirmText: 'This action cannot be undone', profileCreated: 'Profile created!', profileUpdated: 'Profile updated!', usersAssigned: 'user(s) assigned' },
  permissions: { title: 'Permission Management', newPermission: 'New Permission', editPermission: 'Edit Permission', createPermission: 'Create Permission', noPermissions: 'No permissions found', noPermissionsHint: 'Create a new permission with the "New Permission" button', permissionName: 'Permission Name*', permissionCode: 'Code*', assignToUser: 'Assign Permissions to User', deleteConfirmTitle: 'Delete permission?', permissionCreated: 'Permission created!', permissionUpdated: 'Permission updated!' },
  campaigns: { title: 'Campaigns', newCampaign: 'New Campaign', editCampaign: 'Edit campaign', noData: 'No campaigns', viewRecordings: 'View recordings', viewIndicators: 'View & edit indicators', deleteConfirmTitle: 'Delete campaign?', deleteConfirmText: 'This action cannot be undone', campaignCreated: 'Campaign created!', campaignUpdated: 'Campaign updated!', campaignDeleted: 'Campaign deleted!', campaignActivated: 'Campaign activated!', campaignDeactivated: 'Campaign deactivated', saveIndicators: 'Save indicators', savingIndicators: 'Saving...', errorLoading: 'Could not load campaigns', errorSaving: 'Could not save campaign', errorDeleting: 'Could not delete campaign', errorStatus: 'Could not update status', promptEvaluation: 'Evaluation prompt', instructionPrompt: 'Instructions for the AI model...', allowedUsers: 'Allowed users', allowedUsersHint: 'Only selected users will be able to see this campaign, its analysis and reports.', minutesLimit: 'Transcribed minutes limit', minutesLimitHint: 'When this limit is reached, the campaign will be automatically deactivated.', minutesLimitMax: 'Maximum minutes', minutesConsumed: 'Minutes consumed', minutesLimitReached: '⚠ Limit reached — the campaign is inactive.', minutesLimitWarning: '⚠ The campaign will be deactivated when the configured limit is reached.', modify: 'Modify', selectUsers: 'Select users', noneSelected: 'None selected', selectVisible: 'Select visible', deselectVisible: 'Deselect visible', searchUsers: 'Search by name, email or username...', noUsersSelected: 'No users selected — only admins will see the campaign.', selectAllowed: 'Select allowed users' },
  indicatorForm: {
    title: 'Indicators', titleSing: 'Indicator', newIndicator: 'New indicator',
    editingIndicator: 'Editing indicator', indicatorName: 'Name',
    namePlaceholder: 'E.g.: Cordial greeting', scoreIfMeets: 'Score if meets',
    scoreIfNotMeets: 'Score if not meets', condition: 'Condition',
    selectCondition: 'Select condition', description: 'Gemini criteria',
    descriptionPlaceholder: 'Describe in detail what Gemini should look for when evaluating this indicator. You can include examples, activation conditions and edge cases.',
    noIndicators: 'No indicators.', noIndicatorsHint: 'Add at least one.',
    criteriaLabel: 'criteria',
    criteriaHint: 'Precise instructions sent to Gemini to evaluate this indicator. You can include criteria, examples or activation conditions.',
  },
  speech: { title: 'Speech Analytics', upload: 'Upload Audio', transcribe: 'Transcribe', newAudio: 'New Audio', uploadAudio: 'Upload Audio', processing: 'Processing...', analyzing: 'Analyzing...', selectAudio: 'Click to select an audio file', audioFormats: 'MP3, WAV, M4A, OGG — max. 50MB', audioProcessed: 'Audio processed', qualityIndicators: 'Quality Indicators', transcription: 'Transcription', summary: 'Summary', sentiment: 'Sentiment', score: 'Score', duration: 'Duration', analysisResult: 'Analysis result', reviewIndicator: 'Indicator review', previewOnly: 'Preview only', gemini: 'Gemini', originalScore: 'Original score', lastReview: 'Last review', evidence: 'Evidence', meetsIndicator: 'Does it meet the indicator?', yes: 'Yes', no: 'No', meets: 'Yes, meets', doesNotMeet: 'Does not meet', assignedScore: 'Assigned score', range: 'range', auditorNote: 'Auditor note', optional: 'optional', notePlaceholder: 'Justification or comment about the review...', saveReview: 'Save review', applyChanges: 'Apply changes', formatInvalid: 'Invalid format', formatInvalidText: 'Only audio files are allowed', errorUploading: 'Upload error', errorUploadText: 'Could not process audio', errorAnalyzing: 'Analysis error', errorAnalyzeText: 'Could not get transcription', reviewSaved: 'Review saved', errorSavingReview: 'Error', errorSavingReviewText: 'Could not save the review.', resolution: 'Resolution', resolved: 'Resolved', noResolution: 'No resolution', compliance: 'Compliance', script: 'Script', scriptMeets: 'Meets', scriptFails: 'Does not meet', errors: 'Errors', conformity: 'Conformity', applyOk: 'Apply OK', points: 'pts', noEvidenceFound: 'No evidence found in the audio', audited: 'Audited', markAsAudited: 'Mark as audited', alreadyAudited: 'Audited by', auditError: 'Could not mark as audited', Reanalyze: 'Re-analyze with Gemini' },
  reports: { title: 'Reports', subtitle: 'Campaign analytics and statistics', filters: 'Filters', filtersTitle: 'Report filters', campaign: 'Campaign', user: 'User', dateFrom: 'Date from', dateTo: 'Date to', apply: 'Apply filters', clearFilters: 'Clear filters', totalCalls: 'Total recordings', analyzedCalls: 'Analyzed', avgScore: 'Average score', avgDuration: 'Average duration', scoreDistribution: 'Score distribution', callsByUser: 'Recordings by user', callsByCampaign: 'Recordings by campaign', callsOverTime: 'Temporal evolution', sentimentDistribution: 'Sentiment distribution', wordCloud: 'Word cloud', topWords: 'Frequent words', noData: 'No data', noDataDesc: 'No analyzed recordings match the selected filters', exportXlsx: 'Export Excel', exportPdf: 'Export PDF', exporting: 'Exporting...', exportSuccess: 'Exported successfully!', exportError: 'Export error', scoreLabel: 'Score', countLabel: 'Count', userLabel: 'User', dateLabel: 'Date', campaignLabel: 'Campaign', sentimentLabel: 'Sentiment', positive: 'Positive', neutral: 'Neutral', negative: 'Negative', satisfied: 'Satisfied', unsatisfied: 'Unsatisfied', callName: 'Recording', status: 'Status', score: 'Score', duration: 'Duration', date: 'Date', summary: 'Summary', reportTitle: 'Campaign Report', generatedOn: 'Generated on', appliedFilters: 'Applied filters', allCampaigns: 'All campaigns', allUsers: 'All users', indicator: 'Indicator', compliance: 'Compliance', points: 'Points', indicators: 'Indicators', indicatorReport: 'Indicator report', callDetail: 'Recording detail', periodFrom: 'Period from', periodTo: 'to', totalIndicators: 'Total indicators', avgCompliance: 'Average compliance', topIndicators: 'Top indicators', worstIndicators: 'Indicators to improve', indicatorRanking: 'Indicator ranking' },
  login: { welcome: 'Welcome', subtitle: 'Enter your credentials to continue', emailPlaceholder: 'email', passwordPlaceholder: 'password', loginButton: 'Log In', recoverPassword: 'Recover Password', loggingIn: 'Logging in...', errorTitle: 'Authentication error', errorText: 'Incorrect username or password' },
  dashboard: { title: 'Dashboard', contactAdmin: 'Contact an administrator', welcome: 'Welcome' },
  errors: { generic: 'Error', notFound: 'Not found', forbidden: 'Access denied' },
  billing: { title: 'Billing', adminSubtitle: 'Costs, prices and margins per campaign', clientSubtitle: 'Transcribed minutes usage summary', pricePerMin: 'Price / min', period: 'Period', periodStart: 'Period start', days: 'Days', periodNotSet: 'Not configured', notConfigured: 'Not set', renewsIn: 'Renews in {n}d', renewNow: 'Renew now', renewConfirm: 'Renew period for "{name}" now?\nMinutes will be reset and the campaign reactivated if deactivated by limit.', renewSuccess: 'Period renewed. {discarded} recordings discarded.', reactivated: 'Campaign reactivated.', minutes: 'Minutes', minutesUsed: 'Minutes used', limit: 'Limit', noLimit: 'No limit', geminiCost: 'Gemini cost', clientPrice: 'To bill', margin: 'Margin', subtotal: 'Subtotal', totalMinutes: 'Total minutes', geminiCostTotal: 'Total Gemini cost', totalToBill: 'Total to bill', totalMargin: 'Total margin', allCampaigns: 'All campaigns', toClients: 'to clients', currentPeriod: 'current period total', estimatedTotal: 'Estimated total', detailByCampaign: 'Detail by campaign', noCampaigns: 'No campaigns configured.', noPriceWarning: 'Some campaigns have no price configured. Contact your administrator.', noData: 'No data available.', renewConfirmTitle: 'Renew period?', renewConfirmText: 'Minutes will be reset and the campaign will be reactivated if it was inactive due to the limit.', renewedTitle: 'Period renewed', filterTitle: 'Filter billing', filterPeriod: 'Period', filterFrom: 'From...', filterTo: 'To...', selectDate: 'Select...', campaignWord: 'campaigns', configTitle: 'Configure' },
}

// ─── Português ─────────────────────────────────────────────────────────────
const pt: Translations = {
  sidebar: { menu: 'Menu', principal: 'Principal', services: 'Serviços', settings: 'Configurações', home: 'Início', speech: 'Speech', campaigns: 'Campanhas', reports: 'Relatórios', billing: 'Faturação' },
  settings: { title: 'Configurações', profiles: 'Perfis', users: 'Usuários', permissions: 'Permissões' },
  actions: { save: 'Salvar', cancel: 'Cancelar', create: 'Criar', edit: 'Editar', delete: 'Excluir', update: 'Atualizar', close: 'Fechar', search: 'Buscar', saving: 'Salvando...', loading: 'Carregando...', new: 'Novo', confirm: 'Confirmar', activate: 'Ativar', deactivate: 'Desativar', filters: 'Filtros limpos', export: 'Exportar', exportXlsx: 'Exportar Excel', exportPdf: 'Exportar PDF', apply: 'Aplicar', clearFilters: 'Limpar filtros', add: 'Adicionar', saveChanges: 'Salvar alterações', reanalyzeText: 'A análise atual será excluída e a gravação será processada novamente. Continuar?' },
  labels: { statusCampaignImprove: '✗ A melhorar', statusCampaignRegular: '~ Regular', statusCampaignGood: '✓ Bom', name: 'Nome', email: 'Email', password: 'Senha', company: 'Empresa', username: 'Usuário', firstName: 'Nome', lastName: 'Sobrenome', photo: 'Foto de perfil', code: 'Código', active: 'Ativa', inactive: 'Inativa', assignedProfiles: 'Perfis atribuídos', noProfiles: 'Sem perfis atribuídos', myPermissions: 'Minhas Permissões', noPermissions: 'Você não tem permissões atribuídas', fromProfile: 'Do perfil', added: '+ Adicionado', removed: '- Removido', recordings: 'Gravações', analyzed: 'Analisadas', inProgress: 'Em andamento', errors: 'Erros', noCampaigns: 'Sem dados de campanhas ainda', noRecordings: 'Sem gravações analisadas ainda', status: 'Status', campaign: 'Campanha', user: 'Usuário', dateFrom: 'De', dateTo: 'Até', allCampaigns: 'Todas as campanhas', allUsers: 'Todos os usuários', allStatuses: 'Todos os status' },
  userMenu: { myProfile: 'Meu Perfil', assignedProfiles: 'Perfis atribuídos', noProfiles: 'Sem perfis atribuídos', changePassword: 'Alterar Senha', logout: 'Sair', logoutConfirmTitle: 'Sair?', logoutConfirmText: 'Tem certeza que deseja sair?', logoutConfirmBtn: 'Sim, sair', newPassword: 'Nova Senha', confirmPassword: 'Confirmar Nova Senha', updatePassword: 'Atualizar Senha', passwordMinLength: 'A senha deve ter pelo menos 6 caracteres', passwordMismatch: 'As senhas não coincidem', passwordUpdated: 'Senha atualizada!', passwordUpdatedText: 'Sua senha foi atualizada com sucesso', language: 'Idioma' },
  users: { title: 'Gestão de Usuários', newUser: 'Novo Usuário', editUser: 'Editar Usuário', createUser: 'Criar Usuário', noUsers: 'Sem usuários', noUsersHint: 'Crie um novo usuário com o botão "Novo Usuário"', searchByUser: 'Buscar por usuário...', searchByCompany: 'Buscar por empresa...', searching: 'Buscando...', profiles: 'Perfis:', deleteConfirmTitle: 'Excluir usuário?', deleteConfirmText: 'Esta ação não pode ser desfeita', userCreated: 'Usuário criado!', userUpdated: 'Usuário atualizado!', userDeleted: 'Usuário excluído!', profilePhoto: 'Foto de perfil' },
  profiles: { title: 'Gestão de Perfis', newProfile: 'Novo Perfil', editProfile: 'Editar Perfil', createProfile: 'Criar Perfil', noProfiles: 'Sem perfis', noProfilesHint: 'Crie um novo perfil com o botão "Novo Perfil"', profileName: 'Nome do Perfil*', permissions: 'Permissões:', searchUser: 'Buscar usuário por nome ou usuário...', editUser: 'Buscar e Editar Usuário', assignedProfiles: 'Perfis atribuídos:', individualPermissions: 'Permissões individuais:', permissionLegend: '✓ Verde = Do perfil | + Adicionado | - Removido', deleteConfirmTitle: 'Excluir perfil?', deleteConfirmText: 'Esta ação não pode ser desfeita', profileCreated: 'Perfil criado!', profileUpdated: 'Perfil atualizado!', usersAssigned: 'usuário(s) atribuído(s)' },
  permissions: { title: 'Gestão de Permissões', newPermission: 'Nova Permissão', editPermission: 'Editar Permissão', createPermission: 'Criar Permissão', noPermissions: 'Sem permissões', noPermissionsHint: 'Crie uma nova permissão com o botão "Nova Permissão"', permissionName: 'Nome da Permissão*', permissionCode: 'Código*', assignToUser: 'Atribuir Permissões ao Usuário', deleteConfirmTitle: 'Excluir permissão?', permissionCreated: 'Permissão criada!', permissionUpdated: 'Permissão atualizada!' },
  campaigns: { title: 'Campanhas', newCampaign: 'Nova Campanha', editCampaign: 'Editar campanha', noData: 'Sem campanhas', viewRecordings: 'Ver gravações', viewIndicators: 'Ver e editar indicadores', deleteConfirmTitle: 'Excluir campanha?', deleteConfirmText: 'Esta ação não pode ser desfeita', campaignCreated: 'Campanha criada!', campaignUpdated: 'Campanha atualizada!', campaignDeleted: 'Campanha excluída!', campaignActivated: 'Campanha ativada!', campaignDeactivated: 'Campanha desativada', saveIndicators: 'Salvar indicadores', savingIndicators: 'Salvando...', errorLoading: 'Não foi possível carregar as campanhas', errorSaving: 'Não foi possível salvar a campanha', errorDeleting: 'Não foi possível excluir a campanha', errorStatus: 'Não foi possível atualizar o status', promptEvaluation: 'Solicitação de avaliação', instructionPrompt: 'Instruções para o modelo de IA...', allowedUsers: 'Usuários permitidos', allowedUsersHint: 'Somente os usuários selecionados poderão ver esta campanha, suas análises e relatórios.', minutesLimit: 'Limite de minutos transcritos', minutesLimitHint: 'Ao atingir este limite, a campanha será inativada automaticamente.', minutesLimitMax: 'Máximo de minutos', minutesConsumed: 'Minutos consumidos', minutesLimitReached: '⚠ Limite atingido — a campanha está inativa.', minutesLimitWarning: '⚠ A campanha será inativada ao atingir o limite configurado.', modify: 'Modificar', selectUsers: 'Selecionar usuários', noneSelected: 'Nenhum selecionado', selectVisible: 'Selecionar visíveis', deselectVisible: 'Desselecionar visíveis', searchUsers: 'Buscar por nome, email ou usuário...', noUsersSelected: 'Sem usuários selecionados — somente admins verão a campanha.', selectAllowed: 'Selecionar usuários permitidos' },
  indicatorForm: {
    title: 'Indicadores', titleSing: 'Indicador', newIndicator: 'Novo indicador',
    editingIndicator: 'Editando indicador', indicatorName: 'Nome',
    namePlaceholder: 'Ex: Saudação cordial', scoreIfMeets: 'Pontuação se cumpre',
    scoreIfNotMeets: 'Pontuação se não cumpre', condition: 'Condição',
    selectCondition: 'Selecionar condição', description: 'Critério para o Gemini',
    descriptionPlaceholder: 'Descreva em detalhe o que o Gemini deve buscar para avaliar este indicador. Você pode incluir exemplos, condições de ativação e casos limite.',
    noIndicators: 'Sem indicadores.', noIndicatorsHint: 'Adicione pelo menos um.',
    criteriaLabel: 'critério',
    criteriaHint: 'Instruções precisas enviadas ao Gemini para avaliar este indicador. Você pode incluir critérios, exemplos ou condições de ativação.',
  },
  speech: { title: 'Speech Analytics', upload: 'Enviar Áudio', transcribe: 'Transcrever', newAudio: 'Novo Áudio', uploadAudio: 'Enviar Áudio', processing: 'Processando...', analyzing: 'Analisando...', selectAudio: 'Clique para selecionar um arquivo de áudio', audioFormats: 'MP3, WAV, M4A, OGG — máx. 50MB', audioProcessed: 'Áudio processado', qualityIndicators: 'Indicadores de Qualidade', transcription: 'Transcrição', summary: 'Resumo', sentiment: 'Sentimento', score: 'Pontuação', duration: 'Duração', analysisResult: 'Resultado da análise', reviewIndicator: 'Revisão de indicador', previewOnly: 'Apenas visualização', gemini: 'Gemini', originalScore: 'Pontuação original', lastReview: 'Última revisão', evidence: 'Evidência', meetsIndicator: 'O indicador é cumprido?', yes: 'Sim', no: 'Não', meets: 'Sim, cumpre', doesNotMeet: 'Não cumpre', assignedScore: 'Pontuação atribuída', range: 'intervalo', auditorNote: 'Nota do auditor', optional: 'opcional', notePlaceholder: 'Justificativa ou comentário sobre a revisão...', saveReview: 'Salvar revisão', applyChanges: 'Aplicar alterações', formatInvalid: 'Formato inválido', formatInvalidText: 'Apenas arquivos de áudio são permitidos', errorUploading: 'Erro ao enviar', errorUploadText: 'Não foi possível processar o áudio', errorAnalyzing: 'Erro ao analisar', errorAnalyzeText: 'Não foi possível obter a transcrição', reviewSaved: 'Revisão salva', errorSavingReview: 'Erro', errorSavingReviewText: 'Não foi possível salvar a revisão.', resolution: 'Resolução', resolved: 'Resolvido', noResolution: 'Sem resolução', compliance: 'Conformidade', script: 'Script', scriptMeets: 'Cumpre', scriptFails: 'Não cumpre', errors: 'Erros', conformity: 'Conformidade', applyOk: 'Aplicam OK', points: 'pts', noEvidenceFound: 'Nenhuma evidência encontrada no áudio', audited: 'Auditada', markAsAudited: 'Marcar como auditada', alreadyAudited: 'Auditada por', auditError: 'Não foi possível marcar como auditada', Reanalyze: 'Reanalise com Gemini' },
  reports: { title: 'Relatórios', subtitle: 'Análises e estatísticas de campanhas', filters: 'Filtros', filtersTitle: 'Filtros do relatório', campaign: 'Campanha', user: 'Usuário', dateFrom: 'Data de início', dateTo: 'Data de fim', apply: 'Aplicar filtros', clearFilters: 'Limpar filtros', totalCalls: 'Total de gravações', analyzedCalls: 'Analisadas', avgScore: 'Pontuação média', avgDuration: 'Duração média', scoreDistribution: 'Distribuição de pontuações', callsByUser: 'Gravações por usuário', callsByCampaign: 'Gravações por campanha', callsOverTime: 'Evolução temporal', sentimentDistribution: 'Distribuição de sentimentos', wordCloud: 'Nuvem de palavras', topWords: 'Palavras frequentes', noData: 'Sem dados', noDataDesc: 'Nenhuma gravação analisada corresponde aos filtros selecionados', exportXlsx: 'Exportar Excel', exportPdf: 'Exportar PDF', exporting: 'Exportando...', exportSuccess: 'Exportado com sucesso!', exportError: 'Erro ao exportar', scoreLabel: 'Pontuação', countLabel: 'Quantidade', userLabel: 'Usuário', dateLabel: 'Data', campaignLabel: 'Campanha', sentimentLabel: 'Sentimento', positive: 'Positivo', neutral: 'Neutro', negative: 'Negativo', satisfied: 'Satisfeito', unsatisfied: 'Insatisfeito', callName: 'Gravação', status: 'Status', score: 'Pontuação', duration: 'Duração', date: 'Data', summary: 'Resumo', reportTitle: 'Relatório de Campanhas', generatedOn: 'Gerado em', appliedFilters: 'Filtros aplicados', allCampaigns: 'Todas as campanhas', allUsers: 'Todos os usuários', indicator: 'Indicador', compliance: 'Conformidade', points: 'Pontos', indicators: 'Indicadores', indicatorReport: 'Relatório de indicadores', callDetail: 'Detalhe de gravações', periodFrom: 'Período de', periodTo: 'até', totalIndicators: 'Total de indicadores', avgCompliance: 'Conformidade média', topIndicators: 'Melhores indicadores', worstIndicators: 'Indicadores a melhorar', indicatorRanking: 'Ranking de indicadores' },
  login: { welcome: 'Bem-vindo', subtitle: 'Insira suas credenciais para continuar', emailPlaceholder: 'email', passwordPlaceholder: 'senha', loginButton: 'Entrar', recoverPassword: 'Recuperar Senha', loggingIn: 'Entrando...', errorTitle: 'Erro de autenticação', errorText: 'Usuário ou senha incorretos' },
  dashboard: { title: 'Dashboard', contactAdmin: 'Entre em contato com um administrador', welcome: 'Bem-vindo' },
  errors: { generic: 'Erro', notFound: 'Não encontrado', forbidden: 'Acesso negado' },
  billing: { title: 'Faturação', adminSubtitle: 'Custos, preços e margens por campanha', clientSubtitle: 'Resumo de consumo de minutos transcritos', pricePerMin: 'Preço / min', period: 'Período', periodStart: 'Início do período', days: 'Dias', periodNotSet: 'Não configurado', notConfigured: 'Não config.', renewsIn: 'Renova em {n}d', renewNow: 'Renovar agora', renewConfirm: 'Renovar o período de "{name}" agora?\nOs minutos serão resetados e a campanha reativada se estava inativa por limite.', renewSuccess: 'Período renovado. {discarded} gravações descartadas.', reactivated: 'Campanha reativada.', minutes: 'Minutos', minutesUsed: 'Minutos usados', limit: 'Limite', noLimit: 'Sem limite', geminiCost: 'Custo Gemini', clientPrice: 'A faturar', margin: 'Margem', subtotal: 'Subtotal', totalMinutes: 'Total de minutos', geminiCostTotal: 'Custo Gemini total', totalToBill: 'Total a faturar', totalMargin: 'Margem total', allCampaigns: 'Todas as campanhas', toClients: 'a clientes', currentPeriod: 'total do período', estimatedTotal: 'Total estimado', detailByCampaign: 'Detalhe por campanha', noCampaigns: 'Sem campanhas configuradas.', noPriceWarning: 'Algumas campanhas não têm preço configurado. Contacte o seu administrador.', noData: 'Sem dados disponíveis.', renewConfirmTitle: 'Renovar período?', renewConfirmText: 'Os minutos serão zerados e a campanha será reativada se estava inativa por limite.', renewedTitle: 'Período renovado', filterTitle: 'Filtrar faturamento', filterPeriod: 'Período', filterFrom: 'De...', filterTo: 'Até...', selectDate: 'Selecionar...', campaignWord: 'campanhas', configTitle: 'Configurar' },
}

// ─── Italiano ──────────────────────────────────────────────────────────────
const it: Translations = {
  sidebar: { menu: 'Menu', principal: 'Principale', services: 'Servizi', settings: 'Impostazioni', home: 'Home', speech: 'Speech', campaigns: 'Campagne', reports: 'Rapporti', billing: 'Fatturazione' },
  settings: { title: 'Impostazioni', profiles: 'Profili', users: 'Utenti', permissions: 'Permessi' },
  actions: { save: 'Salva', cancel: 'Annulla', create: 'Crea', edit: 'Modifica', delete: 'Elimina', update: 'Aggiorna', close: 'Chiudi', search: 'Cerca', saving: 'Salvando...', loading: 'Caricamento...', new: 'Nuovo', confirm: 'Conferma', activate: 'Attiva', deactivate: 'Disattiva', filters: 'Pulisci i filtri', export: 'Esporta', exportXlsx: 'Esporta Excel', exportPdf: 'Esporta PDF', apply: 'Applica', clearFilters: 'Cancella filtri', add: 'Aggiungi', saveChanges: 'Salva modifiche', reanalyzeText: "L'analisi corrente verrà eliminata e la registrazione verrà elaborata nuovamente. Continuare?" },
  labels: { statusCampaignImprove: '✗ Da migliorare', statusCampaignRegular: '~ Regolare', statusCampaignGood: '✓ Buono', name: 'Nome', email: 'Email', password: 'Password', company: 'Azienda', username: 'Utente', firstName: 'Nome', lastName: 'Cognome', photo: 'Foto profilo', code: 'Codice', active: 'Attiva', inactive: 'Inattiva', assignedProfiles: 'Profili assegnati', noProfiles: 'Nessun profilo assegnato', myPermissions: 'I miei permessi', noPermissions: 'Non hai permessi assegnati', fromProfile: 'Dal profilo', added: '+ Aggiunto', removed: '- Rimosso', recordings: 'Registrazioni', analyzed: 'Analizzate', inProgress: 'In corso', errors: 'Errori', noCampaigns: 'Nessun dato campagna ancora', noRecordings: 'Nessuna registrazione analizzata ancora', status: 'Stato', campaign: 'Campagna', user: 'Utente', dateFrom: 'Da', dateTo: 'A', allCampaigns: 'Tutte le campagne', allUsers: 'Tutti gli utenti', allStatuses: 'Tutti gli stati' },
  userMenu: { myProfile: 'Il mio profilo', assignedProfiles: 'Profili assegnati', noProfiles: 'Nessun profilo assegnato', changePassword: 'Modifica Password', logout: 'Esci', logoutConfirmTitle: 'Uscire?', logoutConfirmText: 'Sei sicuro di voler uscire?', logoutConfirmBtn: 'Sì, esci', newPassword: 'Nuova Password', confirmPassword: 'Conferma Nuova Password', updatePassword: 'Aggiorna Password', passwordMinLength: 'La password deve avere almeno 6 caratteri', passwordMismatch: 'Le password non coincidono', passwordUpdated: 'Password aggiornata!', passwordUpdatedText: 'La tua password è stata aggiornata con successo', language: 'Lingua' },
  users: { title: 'Gestione Utenti', newUser: 'Nuovo Utente', editUser: 'Modifica Utente', createUser: 'Crea Utente', noUsers: 'Nessun utente', noUsersHint: 'Crea un nuovo utente con il pulsante "Nuovo Utente"', searchByUser: 'Cerca per utente...', searchByCompany: 'Cerca per azienda...', searching: 'Cercando...', profiles: 'Profili:', deleteConfirmTitle: 'Eliminare utente?', deleteConfirmText: 'Questa azione non può essere annullata', userCreated: 'Utente creato!', userUpdated: 'Utente aggiornato!', userDeleted: 'Utente eliminato!', profilePhoto: 'Foto profilo' },
  profiles: { title: 'Gestione Profili', newProfile: 'Nuovo Profilo', editProfile: 'Modifica Profilo', createProfile: 'Crea Profilo', noProfiles: 'Nessun profilo', noProfilesHint: 'Crea un nuovo profilo con il pulsante "Nuovo Profilo"', profileName: 'Nome Profilo*', permissions: 'Permessi:', searchUser: 'Cerca utente per nome o username...', editUser: 'Cerca e Modifica Utente', assignedProfiles: 'Profili assegnati:', individualPermissions: 'Permessi individuali:', permissionLegend: '✓ Verde = Dal profilo | + Aggiunto | - Rimosso', deleteConfirmTitle: 'Eliminare profilo?', deleteConfirmText: 'Questa azione non può essere annullata', profileCreated: 'Profilo creato!', profileUpdated: 'Profilo aggiornato!', usersAssigned: 'utente/i assegnato/i' },
  permissions: { title: 'Gestione Permessi', newPermission: 'Nuovo Permesso', editPermission: 'Modifica Permesso', createPermission: 'Crea Permesso', noPermissions: 'Nessun permesso', noPermissionsHint: 'Crea un nuovo permesso con il pulsante "Nuovo Permesso"', permissionName: 'Nome Permesso*', permissionCode: 'Codice*', assignToUser: 'Assegna Permessi a Utente', deleteConfirmTitle: 'Eliminare permesso?', permissionCreated: 'Permesso creato!', permissionUpdated: 'Permesso aggiornato!' },
  campaigns: { title: 'Campagne', newCampaign: 'Nuova Campagna', editCampaign: 'Modifica campagna', noData: 'Nessuna campagna', viewRecordings: 'Vedi registrazioni', viewIndicators: 'Vedi e modifica indicatori', deleteConfirmTitle: 'Eliminare campagna?', deleteConfirmText: 'Questa azione non può essere annullata', campaignCreated: 'Campagna creata!', campaignUpdated: 'Campagna aggiornata!', campaignDeleted: 'Campagna eliminata!', campaignActivated: 'Campagna attivata!', campaignDeactivated: 'Campagna disattivata', saveIndicators: 'Salva indicatori', savingIndicators: 'Salvando...', errorLoading: 'Impossibile caricare le campagne', errorSaving: 'Impossibile salvare la campagna', errorDeleting: 'Impossibile eliminare la campagna', errorStatus: 'Impossibile aggiornare lo stato', promptEvaluation: 'Richiesta di valutazione', instructionPrompt: 'Istruzioni per il modello di intelligenza artificiale...', allowedUsers: 'Utenti autorizzati', allowedUsersHint: 'Solo gli utenti selezionati potranno vedere questa campagna, le sue analisi e i rapporti.', minutesLimit: 'Limite di minuti trascritti', minutesLimitHint: 'Al raggiungimento di questo limite, la campagna verrà disattivata automaticamente.', minutesLimitMax: 'Massimo di minuti', minutesConsumed: 'Minuti consumati', minutesLimitReached: '⚠ Limite raggiunto — la campagna è inattiva.', minutesLimitWarning: '⚠ La campagna verrà disattivata al raggiungimento del limite configurato.', modify: 'Modifica', selectUsers: 'Seleziona utenti', noneSelected: 'Nessuno selezionato', selectVisible: 'Seleziona visibili', deselectVisible: 'Deseleziona visibili', searchUsers: 'Cerca per nome, email o utente...', noUsersSelected: 'Nessun utente selezionato — solo gli admin vedranno la campagna.', selectAllowed: 'Seleziona utenti consentiti' },
  indicatorForm: {
    title: 'Indicatori', titleSing: 'Indicatore', newIndicator: 'Nuovo indicatore',
    editingIndicator: 'Modifica indicatore', indicatorName: 'Nome',
    namePlaceholder: 'Es: Saluto cordiale', scoreIfMeets: 'Punteggio se soddisfa',
    scoreIfNotMeets: 'Punteggio se non soddisfa', condition: 'Condizione',
    selectCondition: 'Seleziona condizione', description: 'Criteri per Gemini',
    descriptionPlaceholder: 'Descrivi in dettaglio cosa deve cercare Gemini per valutare questo indicatore. Puoi includere esempi, condizioni di attivazione e casi limite.',
    noIndicators: 'Nessun indicatore.', noIndicatorsHint: 'Aggiungine almeno uno.',
    criteriaLabel: 'criteri',
    criteriaHint: 'Istruzioni precise inviate a Gemini per valutare questo indicatore. Puoi includere criteri, esempi o condizioni di attivazione.',
  },
  speech: { title: 'Speech Analytics', upload: 'Carica Audio', transcribe: 'Trascrivi', newAudio: 'Nuovo Audio', uploadAudio: 'Carica Audio', processing: 'Elaborazione...', analyzing: 'Analisi...', selectAudio: 'Clicca per selezionare un file audio', audioFormats: 'MP3, WAV, M4A, OGG — max. 50MB', audioProcessed: 'Audio elaborato', qualityIndicators: 'Indicatori di Qualità', transcription: 'Trascrizione', summary: 'Riepilogo', sentiment: 'Sentiment', score: 'Punteggio', duration: 'Durata', analysisResult: 'Risultato analisi', reviewIndicator: 'Revisione indicatore', previewOnly: 'Solo anteprima', gemini: 'Gemini', originalScore: 'Punteggio originale', lastReview: 'Ultima revisione', evidence: 'Evidenza', meetsIndicator: "L'indicatore è soddisfatto?", yes: 'Sì', no: 'No', meets: 'Sì, soddisfa', doesNotMeet: 'Non soddisfa', assignedScore: 'Punteggio assegnato', range: 'intervallo', auditorNote: "Nota dell'auditor", optional: 'opzionale', notePlaceholder: 'Giustificazione o commento sulla revisione...', saveReview: 'Salva revisione', applyChanges: 'Applica modifiche', formatInvalid: 'Formato non valido', formatInvalidText: 'Sono consentiti solo file audio', errorUploading: 'Errore di caricamento', errorUploadText: "Impossibile elaborare l'audio", errorAnalyzing: 'Errore di analisi', errorAnalyzeText: 'Impossibile ottenere la trascrizione', reviewSaved: 'Revisione salvata', errorSavingReview: 'Errore', errorSavingReviewText: 'Impossibile salvare la revisione.', resolution: 'Risoluzione', resolved: 'Risolto', noResolution: 'Nessuna risoluzione', compliance: 'Conformità', script: 'Script', scriptMeets: 'Soddisfa', scriptFails: 'Non soddisfa', errors: 'Errori', conformity: 'Conformità', applyOk: 'Applicano OK', points: 'pts', noEvidenceFound: "Nessuna evidenza trovata nell'audio", audited: 'Controllata', markAsAudited: 'Segna come controllata', alreadyAudited: 'Controllata da', auditError: 'Impossibile segnare come controllata', Reanalyze: 'Rianalizzare con Gemini' },
  reports: { title: 'Report', subtitle: 'Analisi e statistiche delle campagne', filters: 'Filtri', filtersTitle: 'Filtri del rapporto', campaign: 'Campagna', user: 'Utente', dateFrom: 'Data da', dateTo: 'Data a', apply: 'Applica filtri', clearFilters: 'Cancella filtri', totalCalls: 'Totale registrazioni', analyzedCalls: 'Analizzate', avgScore: 'Punteggio medio', avgDuration: 'Durata media', scoreDistribution: 'Distribuzione punteggi', callsByUser: 'Registrazioni per utente', callsByCampaign: 'Registrazioni per campagna', callsOverTime: 'Evoluzione temporale', sentimentDistribution: 'Distribuzione sentimenti', wordCloud: 'Nuvola di parole', topWords: 'Parole frequenti', noData: 'Nessun dato', noDataDesc: 'Nessuna registrazione analizzata corrisponde ai filtri selezionati', exportXlsx: 'Esporta Excel', exportPdf: 'Esporta PDF', exporting: 'Esportando...', exportSuccess: 'Esportato con successo!', exportError: 'Errore di esportazione', scoreLabel: 'Punteggio', countLabel: 'Quantità', userLabel: 'Utente', dateLabel: 'Data', campaignLabel: 'Campagna', sentimentLabel: 'Sentimento', positive: 'Positivo', neutral: 'Neutro', negative: 'Negativo', satisfied: 'Soddisfatto', unsatisfied: 'Insoddisfatto', callName: 'Registrazione', status: 'Stato', score: 'Punteggio', duration: 'Durata', date: 'Data', summary: 'Riepilogo', reportTitle: 'Rapporto Campagne', generatedOn: 'Generato il', appliedFilters: 'Filtri applicati', allCampaigns: 'Tutte le campagne', allUsers: 'Tutti gli utenti', indicator: 'Indicatore', compliance: 'Conformità', points: 'Punti', indicators: 'Indicatori', indicatorReport: 'Rapporto indicatori', callDetail: 'Dettaglio registrazioni', periodFrom: 'Periodo da', periodTo: 'a', totalIndicators: 'Totale indicatori', avgCompliance: 'Conformità media', topIndicators: 'Migliori indicatori', worstIndicators: 'Indicatori da migliorare', indicatorRanking: 'Ranking degli indicatori' },
  login: { welcome: 'Benvenuto', subtitle: 'Inserisci le tue credenziali per continuare', emailPlaceholder: 'email', passwordPlaceholder: 'password', loginButton: 'Accedi', recoverPassword: 'Recupera Password', loggingIn: 'Accesso in corso...', errorTitle: 'Errore di autenticazione', errorText: 'Utente o password non corretti' },
  dashboard: { title: 'Dashboard', contactAdmin: 'Contatta un amministratore', welcome: 'Benvenuto' },
  errors: { generic: 'Errore', notFound: 'Non trovato', forbidden: 'Accesso negato' },
  billing: { title: 'Fatturazione', adminSubtitle: 'Costi, prezzi e margini per campagna', clientSubtitle: 'Riepilogo del consumo di minuti trascritti', pricePerMin: 'Prezzo / min', period: 'Periodo', periodStart: 'Inizio del periodo', days: 'Giorni', periodNotSet: 'Non configurato', notConfigured: 'Non config.', renewsIn: 'Rinnova in {n}g', renewNow: 'Rinnova ora', renewConfirm: 'Rinnovare il periodo di "{name}" ora?\nI minuti verranno azzerati e la campagna riattivata se era inattiva per limite.', renewSuccess: 'Periodo rinnovato. {discarded} registrazioni scartate.', reactivated: 'Campagna riattivata.', minutes: 'Minuti', minutesUsed: 'Minuti usati', limit: 'Limite', noLimit: 'Senza limite', geminiCost: 'Costo Gemini', clientPrice: 'Da fatturare', margin: 'Margine', subtotal: 'Subtotale', totalMinutes: 'Totale minuti', geminiCostTotal: 'Costo Gemini totale', totalToBill: 'Totale da fatturare', totalMargin: 'Margine totale', allCampaigns: 'Tutte le campagne', toClients: 'ai clienti', currentPeriod: 'totale del periodo', estimatedTotal: 'Totale stimato', detailByCampaign: 'Dettaglio per campagna', noCampaigns: 'Nessuna campagna configurata.', noPriceWarning: 'Alcune campagne non hanno un prezzo configurato. Contatta il tuo amministratore.', noData: 'Nessun dato disponibile.', renewConfirmTitle: 'Rinnovare il periodo?', renewConfirmText: 'I minuti verranno azzerati e la campagna verrà riattivata se era inattiva per limite.', renewedTitle: 'Periodo rinnovato', filterTitle: 'Filtra fatturazione', filterPeriod: 'Periodo', filterFrom: 'Da...', filterTo: 'A...', selectDate: 'Seleziona...', campaignWord: 'campagne', configTitle: 'Configura' },
}

export const translations: Record<Locale, Translations> = { es, en, pt, it }

export const localeLabels: Record<Locale, string> = {
  es: '🇦🇷 Español',
  en: '🇺🇸 English',
  pt: '🇧🇷 Português',
  it: '🇮🇹 Italiano',
}